name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Genel İstatistikler (github-metrics.svg)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_languages: yes
          plugin_languages_sections: most-used

      # 2. Skyline Görseli (github-metrics-plugin-skyline.svg)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-plugin-skyline.svg
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2025 # 2026 henüz desteklenmiyor olabilir, 2025 en garantisi
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
